version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo "==================== start build =============================="
      - run: mkdir -p myWorkspace
      - run: echo "Trying out workspaces" > myWorkspace/echo-output
      - persist_to_workspace:
        # Must be an absolute path, or relative path from working_directory
        root: myWorkspace
        # Must be relative path from root
        paths:
          - echo-output 
      - run:
          command: |
            git clone https://github.com/theme-next/hexo-theme-next themes/next
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            git config --global user.email "540518665@qq.com"
            git config --global user.name "weiqian93"
      - run:
          command: |
            yarn build
            yarn deploy
      - run: echo "==================== end build =============================="


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master