version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "65:91:8d:7d:61:20:56:02:37:20:72:fb:7d:d5:4e:49"
      - checkout
      - run: echo "==================== start build =============================="
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output 
      - run:
          command: |
            git clone https://github.com/theme-next/hexo-theme-next themes/next
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            yarn build
            git config --global user.name "weiqian825"
            git config --global user.email "540518665@qq.com"
            yarn deploy
      - run: echo "==================== end build =============================="


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master